### ISSUE TITLE
using incompatiable agent

### ISSUE THREAD

**Issue by mihcox** [ninthwalker/NowShowing#100]
I am getting "ERROR -- : TV Show * using incompatiable agent" for nearly every show in my recording list except 48 hours and guys grocery games. Is there anything that would cause this?

I made sure to change my agents in Plex, then rescan metadata for my entire library.

**Comment by ninthwalker** [comment]
Sorry, real life has caught up and I don't have as much time to work on these side projects as I used to.
If you have the TV agent set to the TVDB or use the 'plex' one that you also set to use the tvdb it might get rid of your errors. If you already set that, then im not quite sure. sorry.
