### ISSUE TITLE
Updating docker template in unRAID doesn't update config.yaml if the file exists

### ISSUE THREAD

**Issue by GroxyPod** [ninthwalker/NowShowing#20]
Updating the docker template to change information will not update the config.yaml file if it already exists. This needs to be changed so that the config.yaml file will be updated in the event someone wants to change their configuration.

We will need to add every possible option to the docker template in order to facilitate this.

**Comment by ninthwalker** [comment]
Advanced config file created. Holds all non-essential configurations. Main config will be updated with the needed variables from template. Advanced will not be overwritten unless it doesn't exist.
