### ISSUE TITLE
Direct Link to plex item

### ISSUE THREAD

**Issue by richowen** [ninthwalker/NowShowing#28]
nice app, would use it if the user could click on a plex item and be taken right to the item in plex, like {plexurl} notification tag in plexpy.

**Comment by ninthwalker** [comment]
Having no direct link to Plex allows better anonymity. However, we can look into adding this as an option instead of the IMDB link in the future.

**Comment by ninthwalker** [comment]
We've decided not to do this type of link. Closing.
