### ISSUE TITLE
Allow selection of Libraries to report on

### ISSUE THREAD

**Issue by ninthwalker** [ninthwalker/NowShowing#31]

**Comment by slamanna212** [comment]
This is the only thing preventing me from using this app. I would really love this feature!

**Comment by SlothCroissant** [comment]
+1. I have a 4K library that I don't share externally due to bandwidth restrictions. I'd love to avoid sending people the new movies added there, as it's confusing to the users. Not the biggest issue in the world, but would be nice.

**Comment by ninthwalker** [comment]
available now in the Dev branch and will be put in the new v2 that is coming out soon

**Comment by ninthwalker** [comment]
Closing. v2 Beta is now finished and available.
