### ISSUE TITLE
Year not being added to movies in email

### ISSUE THREAD

**Issue by SlothCroissant** [ninthwalker/NowShowing#36]
Everything is running flawlessly, but I'm having a strange issue where the year isn't being added to the email. See the attached screenshot, but the gist is that instead of `The Perfect Storm (2000)`, it shows as `The Perfect Storm()`.

Thoughts on if I'm doing something wrong?

![img_0525](https://cloud.githubusercontent.com/assets/5846854/26732035/cca096be-477b-11e7-9bbc-ff2905b032d2.PNG)

**Comment by ninthwalker** [comment]
Sorry for not replying sooner.
See this link for why:
https://forums.lime-technology.com/topic/56483-support-ninthwalker-nowshowing/?do=findComment&comment=563979

**Comment by ninthwalker** [comment]
This is fixed in Dev  with a temporary workaround.
Will merge into master soon
