### ISSUE TITLE
Test email

### ISSUE THREAD

**Issue by justinglock40** [ninthwalker/NowShowing#42]
Despite having changed the settings in the advanced.yml file
I continue to get the following

<img width="485" alt="screenshot at sep 16 17-02-21" src="https://user-images.githubusercontent.com/23133649/30516321-4619576e-9b01-11e7-91dc-74e81e97a24f.png">

Using Kitematic on Windows. Can you tell me what I can do to fix it?

<img width="674" alt="screenshot at sep 16 17-07-09" src="https://user-images.githubusercontent.com/23133649/30516329-74d9f0ea-9b01-11e7-9e8d-2bd392bd73bf.png">

**Comment by ninthwalker** [comment]
I've never used Kitematic. Where did you enter in all the variables at?

**Comment by justinglock40** [comment]
In the docker-compose.yaml

**Comment by justinglock40** [comment]
<img width="692" alt="screenshot at sep 16 17-26-47" src="https://user-images.githubusercontent.com/23133649/30516413-3b577aba-9b04-11e7-90d9-b3d69da32fcb.png">

**Comment by ninthwalker** [comment]
And kitematic executes that yaml file when it starts the docker?
Honestly, I would probably have to install Kitematic and test to see how it works with it, otherwise I'm just guessing on stuff for you.

**Comment by justinglock40** [comment]
Not exactly sure because if did this wouldn't be an issue. However, it pulls all the right data from plex and sends an email to me as the server owner, but everyone else to receive the email I have to manually do the docker exec command

**Comment by ninthwalker** [comment]
oh, i see the issue. It doesn't like the cron format that you entered for the emailonly line.
Try changing that up.

**Comment by justinglock40** [comment]
Still getting parsing error. Even I change it back to original the cron still sends on the time is set. It just sends as a test so no one gets it.

**Comment by ninthwalker** [comment]
If I have time this weekend I'll fool around with Kitematic and let you know what I come up with then

**Comment by ninthwalker** [comment]
Oh, make sure to restart the docker after you change the cron too

**Comment by justinglock40** [comment]
Ok cool

**Comment by justinglock40** [comment]
Got it working had to go miss with the config files in the /opt/ folder

**Comment by ninthwalker** [comment]
Glad you figured it out. Sorry i didn't get around to messing with Kitematic.
