### ISSUE TITLE
Not working with Marvel's The Punisher

### ISSUE THREAD

**Issue by christronyxyocum** [ninthwalker/NowShowing#43]
Seems that NowShowing doesn't handle 404 errors from theTVDB very well:

`D, [2017-11-18T15:21:38.394907 #70] DEBUG -- : Response from thetvdb for query series/329367/all/en.xml: Code: 404.`
`E, [2017-11-18T15:21:38.395176 #70] ERROR -- : Could not connect to thetvdb.com.  Will retry in 30 seconds`
`D, [2017-11-18T15:22:08.395416 #70] DEBUG -- : Retry attempt: 1 for query series/329367/all/en.xml`
`D, [2017-11-18T15:22:08.811694 #70] DEBUG -- : Response from thetvdb for query series/329367/all/en.xml: Code: 404.`
`E, [2017-11-18T15:22:08.811903 #70] ERROR -- : Could not connect to thetvdb.com.  Will retry in 30 seconds`
`D, [2017-11-18T15:22:38.812429 #70] DEBUG -- : Retry attempt: 2 for query series/329367/all/en.xml`
`D, [2017-11-18T15:22:39.130871 #70] DEBUG -- : Response from thetvdb for query series/329367/all/en.xml: Code: 404.`
`E, [2017-11-18T15:22:39.131184 #70] ERROR -- : Could not connect to thetvdb.com.  Will retry in 30 seconds`

It's looking for Marvel's The Punisher w/ seriesID 329367, which is wrong. The correct ID is 331980. Not sure whether it gets the ID from Plex, which would be weird because Plex has all the right metadata, or just from a search, but it shouldn't just repeatedly fail on a 404. It should retry X times and then move on.

**Comment by ninthwalker** [comment]
Thanks for the bugreport. It is suppose to only try 3x, then fail out, so I will have to do some testing.

**Comment by christronyxyocum** [comment]
No problem. Let me know if there's anything I can do to help. Also, is it supposed to fail out for that episode after three failures or out of the script entirely?

**Comment by ninthwalker** [comment]
It’s suppose to fail out of just that movie/ep check and continue on.

**Comment by suckerfish** [comment]
fwiw, getting the same thing for Mindhunter. It seems to be querying an invalid ID to tvdb and getting a 404 according to verbose logging but continues to retry.

**Comment by christronyxyocum** [comment]
> Or at the very least, somehow tell it to ignore the show giving the particular problem?

ninthwalker stated that it's supposed to try three times and then fail, moving on to the next in the list, but there is a bug.

**Comment by ninthwalker** [comment]
I've been a little busy this Month with the holidays. Hope to look into this in January.

**Comment by ninthwalker** [comment]
Closing, fixed in dev version. Will be pushed to prod soon.
Will now correctly try an episode 3x and if not found/errors then will continue on to the next ep.
