### ISSUE TITLE
Something failed.  If you are seeing this, please turn on debugging and open an issue.

### ISSUE THREAD

**Issue by SlothCroissant** [ninthwalker/NowShowing#46]
How does one enable debugging on the [ninthwalker/nowshowing](https://hub.docker.com/r/ninthwalker/nowshowing/) docker image?

I'm having issues where I see the following in my logs:

```
E, [2018-01-12T12:21:12.025291 #808] ERROR -- : Could not connect to thetvdb.com.  Will retry in 30 seconds
E, [2018-01-12T12:21:42.143100 #808] ERROR -- : Could not connect to thetvdb.com.  Will retry in 30 seconds
E, [2018-01-12T12:22:12.437362 #808] ERROR -- : Could not connect to thetvdb.com.  Will retry in 30 seconds
E, [2018-01-12T12:22:42.556812 #808] ERROR -- : Could not connect to thetvdb.com.  Will retry in 30 seconds
E, [2018-01-12T12:23:12.677897 #808] ERROR -- : Could not connect to thetvdb.com.  Will retry in 30 seconds
E, [2018-01-12T12:23:42.781722 #808] ERROR -- : Could not connect to thetvdb.com.  Will retry in 30 seconds
E, [2018-01-12T12:24:12.897743 #808] ERROR -- : Could not connect to thetvdb.com.  Will retry in 30 seconds
E, [2018-01-12T12:24:43.027459 #808] ERROR -- : Could not connect to thetvdb.com.  Will retry in 30 seconds
E, [2018-01-12T12:24:49.907260 #808] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
```

**Comment by ninthwalker** [comment]
See: [https://github.com/ninthwalker/NowShowing/wiki/Command-Line-Options](Command Line Options)
You can also add extra V's for more detail, ie: -vvv

It may be failing on a specific ep, or it could bte tvdb api is having issues. I have heard of late that thetvdb api has been going up/down.

**Comment by christronyxyocum** [comment]
Including the last successful debug message and then all the errors:

`D, [2018-01-16T14:17:07.231818 #869] DEBUG -- : #<HTTParty::Response:0x55eb12f8bd50 parsed_response={"MediaContainer"=>{"size"=>"1", "allowSync"=>"1", "art"=>"/:/resources/show-fanart.jpg", "identifier"=>"com.plexapp.plugins.library", "librarySectionID"=>"29", "librarySectionTitle"=>"UHD TV Shows", "librarySectionUUID"=>"eba54222-a2ec-4cb4-b430-e9e9ff5a069d", "mediaTagPrefix"=>"/system/bundle/media/flags/", "mediaTagVersion"=>"1514426390", "nocache"=>"1", "sortAsc"=>"1", "thumb"=>"/:/resources/show.png", "title1"=>"UHD TV Shows", "title2"=>"All Shows", "viewGroup"=>"show", "viewMode"=>"131122", "Directory"=>{"ratingKey"=>"112110", "key"=>"/library/metadata/112110/children", "studio"=>"BBC One", "type"=>"show", "title"=>"Planet Earth II", "contentRating"=>"TV-G", "summary"=>"David Attenborough presents a documentary series exploring how animals meet the challenges of surviving in the most iconic habitats on earth.\r\n \r\n", "index"=>"1", "rating"=>"9.3", "lastViewedAt"=>"1514923559", "year"=>"2016", "thumb"=>"/library/metadata/112110/thumb/1512021499", "art"=>"/library/metadata/112110/art/1512021499", "banner"=>"/library/metadata/112110/banner/1512021499", "theme"=>"/library/metadata/112110/theme/1512021499", "duration"=>"2700000", "originallyAvailableAt"=>"2016-11-06", "leafCount"=>"6", "viewedLeafCount"=>"0", "childCount"=>"1", "addedAt"=>"1511916529", "updatedAt"=>"1512021499", "Genre"=>[{"tag"=>"Documentary"}, {"tag"=>"Mini-Series"}], "Role"=>[{"tag"=>"David Attenborough"}, {"tag"=>"Charles Tisseyre"}]}}}, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"content-type"=>["text/xml;charset=utf-8"], "content-length"=>["1351"], "connection"=>["close"], "x-plex-protocol"=>["1.0"], "cache-control"=>["no-cache"], "date"=>["Tue, 16 Jan 2018 19:17:07 GMT"]}>
E, [2018-01-16T14:17:07.235190 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.235263 #869] DEBUG -- : ["ratingKey", "112110"]
D, [2018-01-16T14:17:07.235444 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.235681 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.235756 #869] DEBUG -- : ["key", "/library/metadata/112110/children"]
D, [2018-01-16T14:17:07.235802 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.236148 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.236208 #869] DEBUG -- : ["studio", "BBC One"]
D, [2018-01-16T14:17:07.236299 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.236545 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.236649 #869] DEBUG -- : ["type", "show"]
D, [2018-01-16T14:17:07.236738 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.236946 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.237148 #869] DEBUG -- : ["title", "Planet Earth II"]
D, [2018-01-16T14:17:07.237283 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.237466 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.237553 #869] DEBUG -- : ["contentRating", "TV-G"]
D, [2018-01-16T14:17:07.237642 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.237857 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.237977 #869] DEBUG -- : ["summary", "David Attenborough presents a documentary series exploring how animals meet the challenges of surviving in the most iconic habitats on earth.\r\n \r\n"]
D, [2018-01-16T14:17:07.238083 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.238347 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.238419 #869] DEBUG -- : ["index", "1"]
D, [2018-01-16T14:17:07.238547 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.238800 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.238866 #869] DEBUG -- : ["rating", "9.3"]
D, [2018-01-16T14:17:07.239015 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.239217 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.239299 #869] DEBUG -- : ["lastViewedAt", "1514923559"]
D, [2018-01-16T14:17:07.239406 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.239672 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.239741 #869] DEBUG -- : ["year", "2016"]
D, [2018-01-16T14:17:07.239914 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.240141 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.240303 #869] DEBUG -- : ["thumb", "/library/metadata/112110/thumb/1512021499"]
D, [2018-01-16T14:17:07.240370 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.240622 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.240730 #869] DEBUG -- : ["art", "/library/metadata/112110/art/1512021499"]
D, [2018-01-16T14:17:07.240895 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.241273 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.241373 #869] DEBUG -- : ["banner", "/library/metadata/112110/banner/1512021499"]
D, [2018-01-16T14:17:07.241470 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.241709 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.241770 #869] DEBUG -- : ["theme", "/library/metadata/112110/theme/1512021499"]
D, [2018-01-16T14:17:07.241866 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.242054 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.242136 #869] DEBUG -- : ["duration", "2700000"]
D, [2018-01-16T14:17:07.242198 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.242319 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.242448 #869] DEBUG -- : ["originallyAvailableAt", "2016-11-06"]
D, [2018-01-16T14:17:07.242577 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.242871 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.242982 #869] DEBUG -- : ["leafCount", "6"]
D, [2018-01-16T14:17:07.243182 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.243410 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.243525 #869] DEBUG -- : ["viewedLeafCount", "0"]
D, [2018-01-16T14:17:07.243722 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.243943 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.244046 #869] DEBUG -- : ["childCount", "1"]
D, [2018-01-16T14:17:07.244136 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.244448 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.244519 #869] DEBUG -- : ["addedAt", "1511916529"]
D, [2018-01-16T14:17:07.244600 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.244869 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.245007 #869] DEBUG -- : ["updatedAt", "1512021499"]
D, [2018-01-16T14:17:07.245122 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.245438 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.245506 #869] DEBUG -- : ["Genre", [{"tag"=>"Documentary"}, {"tag"=>"Mini-Series"}]]
D, [2018-01-16T14:17:07.245576 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
E, [2018-01-16T14:17:07.245796 #869] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-01-16T14:17:07.245874 #869] DEBUG -- : ["Role", [{"tag"=>"David Attenborough"}, {"tag"=>"Charles Tisseyre"}]]
D, [2018-01-16T14:17:07.245934 #869] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
I, [2018-01-16T14:17:09.415654 #869]  INFO -- : Script complete.  Ran in 60.686475775 seconds
^C
[root@suladan ~]# docker exec -d nowshowing combinedreport -d; tail -f /home/nowshowing/config/nowshowing.log
/usr/local/sbin/combinedreport:255:in `[]'
/usr/local/sbin/combinedreport:255:in `getTVInfo'
/usr/local/sbin/combinedreport:226:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/combinedreport:225:in `each'
/usr/local/sbin/combinedreport:225:in `block in getTVEpisodes'
/usr/local/sbin/combinedreport:212:in `each'
/usr/local/sbin/combinedreport:212:in `getTVEpisodes'
/usr/local/sbin/combinedreport:378:in `main'
/usr/local/sbin/combinedreport:402:in `<main>'
I, [2018-01-16T14:17:09.415654 #869]  INFO -- : Script complete.  Ran in 60.686475775 seconds`

Not sure if this is something with TheTVDB or not.

**Comment by ninthwalker** [comment]
If you run it again is it always with that one show (PE2), or does these errors happen on other shows or movies as well?

**Comment by christronyxyocum** [comment]
Always PE2.

**Comment by ninthwalker** [comment]
So it could be something in the tvdb metadata that the nowshowing program doesn't like.
It's suppose to only try 3x on an EP and then move on. However that logic wasn't working and I recently fixed it in the dev branch. I am pushing the update to production right now, so you could try updating thedocker and running it again and hopefully it will only fail on that series and move on to the rest of the shows.

Let me know. Thanks.

**Comment by christronyxyocum** [comment]
I've been running Dev since you fixed the retry issue. I'll change back to Master and see what happens.

**Comment by christronyxyocum** [comment]
Same thing with PE2 so it's gotta be them. Everything works as expected though.

**Comment by ninthwalker** [comment]
CLosing this for now. Confirirmed is an issue with a specifc show.
Docker has been updated to move on after trying 3x and failing to get metadata for a  show.
Thanks.
