### ISSUE TITLE
Empty Library Freezes NowShowing

### ISSUE THREAD

**Issue by christronyxyocum** [ninthwalker/NowShowing#47]
Please note that I am using the Dev branch as you applied the fixes for failed lookups not failing and moving on.

Looks like having an empty Library in Plex locks up NowShowing. Running with -vvv records this last and it just sits there:

`D, [2018-01-16T13:49:21.844444 #855] DEBUG -- : Debug info for plexmediaserver connection
D, [2018-01-16T13:49:21.844552 #855] DEBUG -- : 200
D, [2018-01-16T13:49:21.844648 #855] DEBUG -- : #<HTTParty::Request:0x000055e4619b60e0 @http_method=Net::HTTP::Get, @path=#<URI::Generic /library/sections/28/all>, @options={:limit=>5, :assume_utf16_is_big_endian=>true, :default_params=>{}, :follow_redirects=>true, :parser=>HTTParty::Parser, :connection_adapter=>HTTParty::ConnectionAdapter, :base_uri=>"http://192.168.1.4:32400", :format=>:xml, :headers=>{"X-Plen-Token"=>"KB4PPvVy2isVepnqBCyz", "X-Plex-Token"=>"KB4PPvVy2isVepnqBCyz"}}, @last_uri=#<URI::HTTP http://192.168.1.4:32400/library/sections/28/all>, @raw_request=#<Net::HTTP::Get GET>, @last_response=#<Net::HTTPOK 200 OK readbody=true>>
D, [2018-01-16T13:49:21.844891 #855] DEBUG -- : #<HTTParty::Response:0x55e4619e4580 parsed_response={"MediaContainer"=>{"size"=>"0", "allowSync"=>"1", "art"=>"/:/resources/movie-fanart.jpg", "identifier"=>"com.plexapp.plugins.library", "librarySectionID"=>"28", "librarySectionTitle"=>"UHD Movies", "librarySectionUUID"=>"b1977f90-c7c6-4430-ba6d-2a141b7b7b38", "mediaTagPrefix"=>"/system/bundle/media/flags/", "mediaTagVersion"=>"1514426390", "sortAsc"=>"1", "thumb"=>"/:/resources/movie.png", "title1"=>"UHD Movies", "title2"=>"All UHD Movies", "viewGroup"=>"movie", "viewMode"=>"131122", "__content__"=>"\n"}}, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"content-type"=>["text/xml;charset=utf-8"], "content-length"=>["484"], "connection"=>["close"], "x-plex-protocol"=>["1.0"], "cache-control"=>["no-cache"], "date"=>["Tue, 16 Jan 2018 18:49:21 GMT"]}>`

After removing the empty Library from Plex, I ran it again and it completed, with the TVDB API issues that they've been having, but it completed. Looks like some logic for an empty Library may need to be applied. I understand that this is most likely an edge case as most users won't have an empty Library, but I had it created waiting for me to find the appropriate content that I wanted to include in it.

**Comment by ninthwalker** [comment]
Hi, yes this is a known issue as mentioned in the wiki/FAQ
https://github.com/ninthwalker/NowShowing/wiki/FAQ

For now you have to have all Libraries full. I’ve looked at the issue before and it’s not an easy fix. =(

**Comment by christronyxyocum** [comment]
Ah, ok. No worries. Sorry for not checking the Wiki. I will close this out.
