### ISSUE TITLE
EOFError when trying to run email or web report.

### ISSUE THREAD

**Issue by alex-baratta** [ninthwalker/NowShowing#48]
My application hasn't sent out an email or updated the now showing area since early December.
when I run the command "docker exec nowshowing webreport"
/usr/local/sbin/webreport: end of file reached (EOFError)

docker exec nowshowing emailreport -d -t
/usr/local/sbin/emailreport: end of file reached (EOFError)

**Comment by ninthwalker** [comment]
What platform are you on? unRaid or a different OS? Also, are you using user/pass or token? 
Anything change that you know of? You could also try adding -vvv at the end of the command at see if it gives you more info in the log.

**Comment by alex-baratta** [comment]
when i start the app in unraid the start up log looks like 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-apply-perms: applying...
[fix-attrs.d] 10-apply-perms: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-set-uidgid: executing...
usermod: no changes

-----------------------------------------
 NowShowing
-----------------------------------------
 Brought to you by:

Ninthwalker/GroxyPod/Limen75

-----------------------------------------
User xyz set to: 99
Group xyz set to: 100
-----------------------------------------

[cont-init.d] 10-set-uidgid: exited 0.
[cont-init.d] 20-setup: executing...
Advanced config file detected. Keeping existing files
Setup complete! Please read directions for advanced settings and changing the schedule.
[cont-init.d] 20-setup: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by alex-baratta** [comment]
here is my log from the last 5 days of activity until now
[nowshowing-last-5-days-of-activity.txt](https://github.com/ninthwalker/NowShowing/files/1639900/nowshowing-last-5-days-of-activity.txt)

**Comment by alex-baratta** [comment]
I think i figured it out I forgot I implemented Plex to do required Secure connections  instead of preferred.
my apologies. 
Clearly P.E.B.C.A.K.
