### ISSUE TITLE
Not All New Unwatched Episodes Showing

### ISSUE THREAD

**Issue by discreet** [ninthwalker/NowShowing#55]
I have multiple newly added (within last 7 days) unwatched episodes for the same show but NowShowing only displays the latest unwatched episode. Is this by design or a bug? It would be nice to get all of the unwatched new (within last 7 days) episodes.

**Comment by ninthwalker** [comment]
I think I just responded to you on reddit.

The app doesn’t look for watches status at all. Only the date added field in Plex. 

It should be reporting all episodes if it’s an existing season. For example, I added 5 episodes from the season 5 voltron cartoon and it listed out all 5ep in the report.

Does the log show anything abnormal or just listing the 1ep? You could try running a test report with -vvv for more verbose output in the log file and see if that sheds any light. 

Make sure you are using thetvdb agent as well as that’s where it will get metadata from. 

Test report to only your email with:

docker exec NowShowing emailreport -t -vvv

- Brent

**Comment by discreet** [comment]
From what I can tell I don't see anything strange in the logs. When I try a `docker exec nowshowing emailreport -t -vvv` I do get a timeout error though.

```
/usr/lib/ruby/2.3.0/net/http.rb:880:in `initialize': execution expired (Net::OpenTimeout)
        from /usr/lib/ruby/2.3.0/net/http.rb:880:in `open'
        from /usr/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'                                       from /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
        from /usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
        from /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from /usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
        from /usr/lib/ruby/2.3.0/net/http.rb:1384:in `request'
        from /usr/lib/ruby/gems/2.3.0/gems/httparty-0.13.1/lib/httparty/request.rb:93:in `perform'           from /usr/lib/ruby/gems/2.3.0/gems/httparty-0.13.1/lib/httparty.rb:521:in `perform_request'
        from /usr/lib/ruby/gems/2.3.0/gems/httparty-0.13.1/lib/httparty.rb:457:in `get'                      from /var/lib/nowshowing/plex.rb:29:in `get'
        from /usr/local/sbin/emailreport:158:in `getMovieInfo'
        from /usr/local/sbin/emailreport:129:in `block (2 levels) in getMovies'                              from /usr/local/sbin/emailreport:128:in `each'
        from /usr/local/sbin/emailreport:128:in `block in getMovies'
        from /usr/local/sbin/emailreport:106:in `each'
        from /usr/local/sbin/emailreport:106:in `getMovies'
        from /usr/local/sbin/emailreport:377:in `main'
        from /usr/local/sbin/emailreport:397:in `<main>'
```

**Comment by ninthwalker** [comment]
Thanks for the update.
I say we wait until next week and if it is continuously missing episodes you have added we can look into that further.

As for the 2 emails, is it to different addresses?
The current production branch of NowShowing sends a unique email to every user or email address you configured. This is changing in v2 which will be released soon to do one email that bcc's everyone instead.

**Comment by ninthwalker** [comment]
Closing for now. v2 Beta is available and has a lot of fixes and feature additions.

**Comment by discreet** [comment]
Just wanted to comment on this and let you know things normalized. I started seeing multiple episodes per series in the email reports. The web reports remained the same however but that's not a big deal.
