### ISSUE TITLE
Possible to edit css on v2 

### ISSUE THREAD

**Issue by markhaines** [ninthwalker/NowShowing#56]
On v1 I've been using an edited version of the CSS file to change some colours to fit with my custom logos.  If I use the admin interface (which is a nice addition btw!) if I make any changes then they'll automatically get overwritten if I save anything through the UI, correct?  

Is this also true if I pull the latest version of the app through Docker each time?

Is there any way to 'protect' my custom changes?

**Comment by ninthwalker** [comment]
Hi, Just finished up with v2. Calling it 'Beta' for now until a few more people test it out, but it should be good to go.

I think a lot of people modify the email/web templates/CSS (myself included).
v1 and v2 both do _not_ overwrite those files if it detects an advanced.yaml file.
So during a fresh install or an update, if it is writing to the same volume docker mapping, it checks for the advanced.yaml file and if it exists doesn't replace any files in the /config mapping.

If you install v2, point it to a fresh directory so it will populate it's files. Use the new web interface to configure. Then just copy over your old files that you have customized.
One thing to note is that a couple files were renamed/directory structure changed for the new version, but everything should be easy to find. I think I maye have changed a couple lines in the style.css file, but nothing of real importance.

Let me know how the new version works out for you. Thanks.
