### ISSUE TITLE
No Docker

### ISSUE THREAD

**Issue by 12nick12** [ninthwalker/NowShowing#64]
Any way to do this without docker?

**Comment by ninthwalker** [comment]
Not easily. 
On Linux you would have to install all the dependencies yourself. 
It uses mainly ruby/gems/php and a few other little things. 

There is ruby for windows but have never used it.

By the time you manually install everything, spinning up docker on your OS would be much quicker.

**Comment by ninthwalker** [comment]
Closing. This is Docker only for now. Thanks.
