### ISSUE TITLE
Announcement textarea gets repositioned after viewing logs in Log Viewer

### ISSUE THREAD

**Issue by Codehhh** [ninthwalker/NowShowing#65]
![image](https://user-images.githubusercontent.com/12055335/38500714-3ae51dfa-3bd9-11e8-8e6f-22f839e5b994.png)

NowShowing Version: 2.0.1
Firefox 59.0.2

**Comment by ninthwalker** [comment]
Thanks for the report. 
Looks like a css formatting mixup. 
I’ll look into fixing that soon, in the meantime an F5 refresh seems to make it look correct again.

**Comment by ninthwalker** [comment]
Can you do me a favor and check something.
In your docker volume mapping, go into the /cfg/ directory and see if there is a 'version' file there?
Thanks.

EDIT: nevermind, I was able to reproduce this display error.

**Comment by Codehhh** [comment]
The version file is there, contains "2.0.1"

**Comment by ninthwalker** [comment]
You responded too quick! lol.
I was able to reproduce the error. Thanks for checking.

**Comment by ninthwalker** [comment]
Fixed in v2-dev. will be pushed to main v2 branch soon.

**Comment by ninthwalker** [comment]
Fixed in 2.0.2
