### ISSUE TITLE
Tautulli Stats

### ISSUE THREAD

**Issue by justinglock40** [ninthwalker/NowShowing#66]
I don't have the statisitics tab? Anything special needing to be done for it?

**Comment by ninthwalker** [comment]
Make sure you grabbed the latest v2 release. It’s 2.0.1 if you check the Tools > Help Links section for the version. 

You may have grabbed v2 beta before the final release which was 2.0.1. Future updates won’t need a fresh install, but this initial v2 does.

**Comment by justinglock40** [comment]
I did docker pull with the newest version, but it returns 2.0.0 as the latest

**Comment by ninthwalker** [comment]
If you did a pull and it still shows 2.0.0 then try mapping to a new volume. If it detects the advanced.yaml file it won’t update certain files.

The logic for v2 upgrades was put in 2.0.1 so you’ll need a fresh install.

**Comment by ninthwalker** [comment]
Going to close this. Once you get the correct 2.0.1 version installed the Stats page will show.
Open another ticket if it doesn't. Thanks.
