### ISSUE TITLE
Movie and TV swapped in Statistics email header.

### ISSUE THREAD

**Issue by SaskiFX** [ninthwalker/NowShowing#67]
I am testing and enabled statistics for the e-mail. I noticed that my listing for Movie and TV are swapped.

Most Watched Movie: | Paw Patrol
Most Watched TV Show: | Bolt

**Comment by ninthwalker** [comment]
I’ll have to see if I can replicate this. 
I haven’t seen this happen before.

**Comment by SaskiFX** [comment]
Sounds good. Also noticed that I only have Movies and TV shows in Plex but the totals line also shows a blank entry for songs.

**Comment by ninthwalker** [comment]
Yea, someone else also pointed out the totals thing. I’ll either remove songs or allow the totals line to be selected for each total.

**Comment by ninthwalker** [comment]
Can you do me a favor and check the version you are on. Check for 2 things please:

Version listed in web interface under: Tools > Help Links.
And can you also check to see if a file called 'version' is present in your mapped docker volume in the /cfg/ directory. Thanks!

**Comment by SaskiFX** [comment]
Sure.

About
    Version: 2.0.1
    Updated: 08APR2018
    Created By: Ninthwalker/GroxyPod/Limen75

The file is present and says 2.0.1

**Comment by ninthwalker** [comment]
Alright, thanks for checking. I haven't been able to reproduce the error yet.
Have you run any more test reports and is this consistent for you?
Also, I'm assuming if you look in Tautulli for the same stats that it shows correctly?
NowShowing should be pulling from the Tautulli stat, so it should report whatever is listed in the field for the top watched movie/tv by plays.

**Comment by SaskiFX** [comment]
Strange. I re-ran the report and it's the same as before. Now I'm running this on the Test Report function. I'm guessing it's pulling live data?

In Tautulli I have my most popular TV is Paw Patrol, but the most popular movie is Last Jedi, Bolt doesn't even appear on the list. 

My most concurrent users is off by one as well, and the same with the total movies counter.

**Comment by ninthwalker** [comment]
Here is something to check since I still can't make it report something that Tautulli isn't sending.
Run a test report with the stats.
Then use this Tautulli endpoint to check the stat in question and see if it matches or says something different. Replace the IP/Port/APIkey with your own. Also if not running the default 7 day report time in NowShowing match that with your value too:

http://192.168.1.10:8181/api/v2?apikey=YourAPIkeyHere&cmd=get_home_stats&time_range=7&stats_type=0

JSON field's to look for:
Top Movie: Response > Data > 1 >Rows > 0 > Title
Top TV: Response > Data > 3 >Rows > 0 > Title

**Comment by SaskiFX** [comment]
Sorry for the late reply. Mine is reversed. 

Response > Data > 1 >Rows > 0 > Title : is the TV entry
Top TV: Response > Data > 3 >Rows > 0 > Title : is the Movie entry

Here are the stat_id's of my rows:

0 - "top_tv"
1 - "popular_tv"
2 - "top_movies"
3 - "popular_movies"
4 - "top_music"
...

etc.

Running v2.0.19-beta of Tautulli.

**Comment by SaskiFX** [comment]
If the whole response would help, I can copy and paste it somewhere. So long as nothing in there should be kept private.

**Comment by ninthwalker** [comment]
Well there’s the problem. 
Thanks for looking at the json fields. 

Tautulli has been out of Beta for a bit. Latest version is now 2.0.28.

The Tautulli Dev must have changed some of the database structure around before final release for the new 2.0 version.

Update to the latest and the fields should be the same as I look for and report correctly. Let me know. Thanks.

**Comment by SaskiFX** [comment]
That has fixed it. Sorry for the hassle. >.<

**Comment by ninthwalker** [comment]
No worries. Thanks for letting me know about the database change.
