### ISSUE TITLE
admin does not exist

### ISSUE THREAD

**Issue by CyberMew** [ninthwalker/NowShowing#72]
Hi, it's been a while since I last tried to configure NowShowing (v1). I updated the docker image, and tried to access serverip:port/admin but to no avail:

Not Found
`/admin' not found.
WEBrick/1.3.1 (Ruby/2.3.7/2018-03-28)

How can I (re)set this up properly again?

**Comment by ninthwalker** [comment]
You are on the old v1. 
The new v2 was a large code rewrite so there isn’t a direct upgrade path from v1. 

Install v2 as a fresh install. 
ninthwalker/nowshowing:v2

**Comment by ninthwalker** [comment]
Closing. Let me know if any issues after switching to v2. Thanks
