### ISSUE TITLE
Errors in logs, no statistics from tautulli showing

### ISSUE THREAD

**Issue by BobOkisama** [ninthwalker/NowShowing#73]
Tautulli VERSION V2.1.1-BETA
The standard report works, but all statistics are missing in web, they do show up in email however.
Logs show:
E, [2018-04-14T06:37:46.229414 #1292] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
I cannot find how to turn on debugging though.. so cannot give too much more info than that.

In email statistics, the most watched movie shows up as a tv episode and there are no most watched tv shows at all listed.

Running on ubuntu 16.04 in docker.

**Comment by ninthwalker** [comment]
Upgrade to the latest version and retest please. 

Also, the latest v2.0.2 version has a ‘Test connection’ button on the stats settings page. So you can make sure that is successful before running a report. 

If still throwing errors, you can drop to the command line and run this for a test email and more verbose logging:

docker exec NowShowingv2 emailreport -t -vv

Or

docker exec NowShowingv2 webreport -t -vv

**Comment by ninthwalker** [comment]
Statistics were just recently added. 
They are available in the email report but not web yet. 

Web is planned for the next small update

**Comment by ninthwalker** [comment]
As for the wrong stat, please update to the latest 2.0.2 release. 
This included a few bug fixes as it relates to the stats.

For more verbose logging, you can drop to command line and run a test report like this:

docker exec NowShowingv2 emailreport -t -vv
Or
docker exec NowShowingv2 webreport -t -vv

Someone else also reported movie/tv being swapped but I can't replicate it.
Here is something to check if it reports wrong:

Run a test report with the stats.
Then use this Tautulli endpoint to check the stat in question and see if it matches or says something different. Replace the IP/Port/APIkey with your own. Also if not running the default 7 day report time in NowShowing match that with your value too:

http://192.168.1.10:8181/api/v2?apikey=YourAPIkeyHere&cmd=get_home_stats&time_range=7&stats_type=0

JSON field's to look for:
Top Movie: Response > Data > 1 >Rows > 0 > Title
Top TV: Response > Data > 3 >Rows > 0 > Title

**Comment by BobOkisama** [comment]
Sorry for delay in reply.. usually when I post something I am johnny on the spot.
Verified running 2.0.2. I did the manual reports and got a lot more logging now.

The bulk of the errors look like:
E, [2018-04-15T05:50:37.802029 #16422] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-04-15T05:50:37.802057 #16422] DEBUG -- : ["contentRating", "TV-14"]
D, [2018-04-15T05:50:37.802087 #16422] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/emailreport:263:in `[]'
/usr/local/sbin/emailreport:263:in `getTVInfo'

/usr/local/sbin/emailreport:234:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/emailreport:233:in `each'
/usr/local/sbin/emailreport:233:in `block in getTVEpisodes'
/usr/local/sbin/emailreport:219:in `each'
/usr/local/sbin/emailreport:219:in `getTVEpisodes'
/usr/local/sbin/emailreport:402:in `main'
/usr/local/sbin/emailreport:420:in `<main>'

and another

D, [2018-04-15T05:50:37.797067 #16422] DEBUG -- : Debug info for plexmediaserver connection
D, [2018-04-15T05:50:37.797137 #16422] DEBUG -- : 200
D, [2018-04-15T05:50:37.797173 #16422] DEBUG -- : #<HTTParty::Request:0x0000558f88e52e10 @http_method=Net::HTTP::Get, @path=#<URI::Generic /library/sections/23/all>, @options={:limit=>5, :assume_utf16_is_big_endian=>true, :default_params=>{}, :follow_redirects=>true, :parser=>HTTParty::Parser, :connection_adapter=>HTTParty::ConnectionAdapter, :base_uri=>"http://x.x.x.x1:32400", :format=>:xml, :headers=>{"X-Plex-Token"=>"xxx"}}, @last_uri=#<URI::HTTP http://x.x.x.x:32400/library/sections/23/all>, @raw_request=#<Net::HTTP::Get GET>, @last_response=#<Net::HTTPOK 200 OK readbody=true>>
D, [2018-04-15T05:50:37.797319 #16422] DEBUG -- : #<HTTParty::Response:0x558f887dd6e8 parsed_response={"MediaContainer"=>{"size"=>"1", "allowSync"=>"1", "art"=>"/:/resources/show-fanart.jpg", "identifier"=>"com.plexapp.plugins.library", "librarySectionID"=>"23", "librarySectionTitle"=>"TV Shows - Comedy Central Presents", "librarySectionUUID"=>"75043285-3c15-4feb-a026-e88dda99df7d", "mediaTagPrefix"=>"/system/bundle/media/flags/", "mediaTagVersion"=>"1523044301", "nocache"=>"1", "thumb"=>"/:/resources/show.png", "title1"=>"TV Shows - Comedy Central Presents", "title2"=>"All Shows", "viewGroup"=>"show", "viewMode"=>"65592", "Directory"=>{"ratingKey"=>"92091", "key"=>"/library/metadata/92091/children", "studio"=>"Comedy Central", "type"=>"show", "title"=>"Comedy Central Presents", "contentRating"=>"TV-14", "summary"=>"Since 1998, Comedy Central Presents has showcased America's finest comedians doing their finest work on the finest stage on television.\r\nIn short, Comedy Central Presents provides every comedy fan's fantasy -- a half-hour alone with the best stand-ups on the scene. Don't miss it when your favorite comedian hits our stage.", "index"=>"1", "rating"=>"8.6", "viewCount"=>"9", "lastViewedAt"=>"1460606400", "year"=>"1998", "thumb"=>"/library/metadata/92091/thumb/1502456810", "art"=>"/library/metadata/92091/art/1502456810", "banner"=>"/library/metadata/92091/banner/1502456810", "theme"=>"/library/metadata/92091/theme/1502456810", "duration"=>"1800000", "originallyAvailableAt"=>"1998-12-01", "leafCount"=>"312", "viewedLeafCount"=>"9", "childCount"=>"16", "addedAt"=>"1402563420", "updatedAt"=>"1502456810", "Genre"=>{"tag"=>"Comedy"}}}}, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"content-type"=>["text/xml;charset=utf-8"], "content-length"=>["1491"], "connection"=>["close"], "x-plex-protocol"=>["1.0"], "cache-control"=>["no-cache"], "date"=>["Sun, 15 Apr 2018 12:50:37 GMT"]}>
E, [2018-04-15T05:50:37.801054 #16422] ERROR -- : Something failed.  If you are seeing this, please turn on debugging and open an issue.
D, [2018-04-15T05:50:37.801103 #16422] DEBUG -- : ["ratingKey", "92091"]
D, [2018-04-15T05:50:37.801137 #16422] DEBUG -- : no implicit conversion of String into Integer (TypeError)
/usr/local/sbin/emailreport:263:in `[]'
/usr/local/sbin/emailreport:263:in `getTVInfo'
/usr/local/sbin/emailreport:234:in `block (2 levels) in getTVEpisodes'
/usr/local/sbin/emailreport:233:in `each'
/usr/local/sbin/emailreport:233:in `block in getTVEpisodes'
/usr/local/sbin/emailreport:219:in `each'
/usr/local/sbin/emailreport:219:in `getTVEpisodes'
/usr/local/sbin/emailreport:402:in `main'
/usr/local/sbin/emailreport:420:in `<main>'

(token and ip xed out of course.)

**Comment by ninthwalker** [comment]
Worked with another guy that reported Erin stats. Looks like he was also on the older Tautulli beta version. It has been out of Beta for a bit. Latest version is now 2.0.28.

The Tautulli Dev must have changed some of the database structure around before final release for the new 2.0 version.

Update to the latest Tautulli version and the fields should be the same as I look for and report correctly. Let me know. Thanks.

Also, to clarify, besides the statistics do you also have another issue with the report not running? Thanks.

**Comment by BobOkisama** [comment]
I am running Tautulli 2.1.1 currently.

**Comment by ninthwalker** [comment]
2.1.1 is the next beta version it looks like.
2.0.28 is the latest stable release.
I'm not sure what the Tautulli dev is changing in the next version, so I have to wait until he makes it stable before I make any changes on my end to account for his changes. I am making my code work for the latest stable version.

**Comment by BobOkisama** [comment]
Fair enough, I expect odd things due to me using beta. Keep up the great work!

**Comment by ninthwalker** [comment]
I am installing tautulli beta right now though to checkout the database structure to see if anything else has changed. I may add an option in the NowShowing stats settings where a user can specify the version of Tautulli so it looks for the correct database mapping

**Comment by BobOkisama** [comment]
Hey, would be awesome if you can throw those stats on the webpage too, would love to have that prominently displayed (totals at least) when someone goes to the page. Wanted to make sure you know I really like this project so far, and am using it already, this is great stuff!

**Comment by ninthwalker** [comment]
Yup, stats were new so only added to email so far.
Web integration is planned real soon. Code part is easy, just need to do the html/css part to make it look good.

**Comment by ninthwalker** [comment]
Closing.
Web stats will be in the next update release in a couple days.
Tautulli database stat part I'll still look into, but will probably not adjust until the next Tautulli stable release.
Thanks.
