### ISSUE TITLE
E-mail send failure - Secure SMTP provider

### ISSUE THREAD

**Issue by 2wheelsdown** [ninthwalker/NowShowing#76]
Hi,

I'm using FastHosts for my e-mail provider with the following SMTP connection settings:

Provider          - Other
SMTP Port       - 465
SMTP Server    - smtp.livemail.co.uk

(FYI - these e-mail settings work fine for sending e-mails out of OMBI)

I'm going to "Tools -> Announcement E-mail" and sending a test e-mail.  After a shortwhile a green "Announcement e-mail sent" message appears near the top but no e-mail is received.

Checking the "NowShowing" logs reveals the following:

```
I, [2018-04-25T11:51:53.432883 #1267]  INFO -- : Announcement Email Sent.

Net::ReadTimeout["/usr/lib/ruby/2.3.0/net/protocol.rb:176:in `rbuf_fill'", "/usr/lib/ruby/2.3.0/net/protocol.rb:154:in `readuntil'", "/usr/lib/ruby/2.3.0/net/protocol.rb:164:in `readline'", "/usr/lib/ruby/2.3.0/net/smtp.rb:967:in `recv_response'", "/usr/lib/ruby/2.3.0/net/smtp.rb:556:in `block in do_start'", "/usr/lib/ruby/2.3.0/net/smtp.rb:977:in `critical'", "/usr/lib/ruby/2.3.0/net/smtp.rb:556:in `do_start'", "/usr/lib/ruby/2.3.0/net/smtp.rb:521:in `start'", "/usr/lib/ruby/gems/2.3.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'", "/usr/lib/ruby/gems/2.3.0/gems/mail-2.6.3/lib/mail/message.rb:252:in `deliver!'", "/var/lib/nowshowing/mailAnnouncement.rb:100:in `sendMail'", "/usr/local/sbin/announcementreport:87:in `main'", "/usr/local/sbin/announcementreport:91:in `
'"]

I, [2018-04-25T11:51:53.432812 #1267]  INFO -- : SMTP mailing failed!
```

Unfortunately I can't discern anything useful from that to help me diagnose this further - can anyone else see anything that could be a clue?  Or are there other logs I can pull from somewhere else? Thanks.

**Comment by ninthwalker** [comment]
If you run it again right after does it succeed or timeout again?

Also try port 587 and let me know if that produces the same error. 

Thanks.

**Comment by 2wheelsdown** [comment]
So tried sending the Announcement E-mail test e-mail twice in a row with the same results.

However, switching over to port 587 cured it - the test e-mails were sending through almost instantly.

So, that's awesome!  Thanks for the suggestions.  But it leaves my wondering the age old "Why?" LOL

As mentoned before, I've got an instance of OMBI running on the same VM (although not inside of Docker) which sends e-mails via port 465...?  When I contacted my e-mail host about some issues sending mail a few months back (OMBI suddenly stopped sending mails), they told me to switch from port 25 (which I had been using for almost a year) to port 465.  No mention of 587 or STARTTLS...

Thanks again Ninthwalker!

**Comment by ninthwalker** [comment]
Glad it worked. 587 is the new standard for secure smtp. The implementation I use, uses the starttls. I’ve thought about changing that, or adding an option, but so far every email provider I’ve come across also offers this standard now. 

The 465 and really old 25 ports are for legacy reasons for the most part. 

Here is a little article about the ports and history as well if interested:

http://blog.mailgun.com/25-465-587-what-port-should-i-use/amp/

**Comment by 2wheelsdown** [comment]
I get that, I knew about 587 being the 'other' potential option, but my provider specifically told me to use 465, and 465 has been working fine (still is) with OMBI's newsletter e-mail function.

**_That's_** the bit that is throwing me for a loop, lol.
