### ISSUE TITLE
Wrong headings in stats.

### ISSUE THREAD

**Issue by elit3ge** [ninthwalker/NowShowing#79]
Just ran the script for the first time and it has the headers wrong for the stats, where it has movies it displays tv and where it has tv it shows movies.

![snap](https://user-images.githubusercontent.com/1644699/42131814-65e72cd0-7d4e-11e8-9923-d3ab9fe4c912.PNG)

**Comment by ninthwalker** [comment]
Thanks for letting me know. It looks like some of the database tables changed in the last couple versions of tautulli. i will need to look into a different way to parse and pull the correct stat.

**Comment by ninthwalker** [comment]
Closing, and will use #94 as the main issue for this bug
