### ISSUE TITLE
TV show background images are not visible in Chrome

### ISSUE THREAD

**Issue by nyid** [ninthwalker/NowShowing#80]
Seems to work fine in Firefox and Edge. The movie backgrounds are visible.

Using the prebuilt docker container with unRAID.

**Comment by ninthwalker** [comment]
Sorry i never commented on this, but I was never able to reproduce this issue and no one else reported anything looking different so maybe it was just your instance of chrome and it's setup

**Comment by dear-clouds** [comment]
Commenting this just to say that there's the same problem on Opera :)

**Comment by Unthred** [comment]
I had the same issue, turns out it was my add blocker that was silently blocking them. If you bring up the chrome dev console F12 hopefully you will see the errors. I just excluded the site in adblocker and it all works fine now
