### ISSUE TITLE
Not seeing option for Tautulli

### ISSUE THREAD

**Issue by rmilyard** [ninthwalker/NowShowing#81]
I am running version 2.0.3 on Now Showing v2.  I am not seeing option to integrate with tautlli.

What might I be missing?

**Comment by rmilyard** [comment]
Anyone looking at isues?

**Comment by ninthwalker** [comment]
Have been busy this week, sorry.
As for not seeing the Tautulli options, what do you see? Can you show me a screenshot of the admin page with the other tabs?

If you are on 2.0.3 you should see it look like this screenshot and the Tautulli options are on the Stats page:

[Admin page](https://raw.githubusercontent.com/ninthwalker/NowShowing/v2/images/ns_v2_menu.png)

**Comment by rmilyard** [comment]
[image1.png]

Sent from my iPhone

On Jul 31, 2018, at 10:04 AM, ninthwalker <notifications@github.com<mailto:notifications@github.com>> wrote:


Have been busy this week, sorry.
As for not seeing the Tautulli options, what do you see? Can you show me a screenshot of the admin page with the other tabs?

If you are on 2.0.3 you should see it look like this screenshot and the Tautulli options are on the Stats page:

<https://raw.githubusercontent.com/ninthwalker/NowShowing/v2/images/ns_v2_menu.png>

**Comment by rmilyard** [comment]
Not sure pic uploaded. I don’t have stats tab at all.

**Comment by ninthwalker** [comment]
saw the screenshots on the unraid forums and the log.
Your install is definitely messed up. It's missing files and other things that should be in your appdata dir for the docker.

Try these options, in order.

1st, stop the docker, go to its docker settings and change the appdata config path to a brand new one with no files. If the docker image is at the latest version it should populate the files in the new dir. You will have to go to the /admin page and enter in your settings again. (You can cheat and look in the old advanced config file in your old config path to get your settings if you want)

If that still doesn't work, then I would re-create the docker image entirely.

**Comment by rmilyard** [comment]
I changed to a new Appdata folder and setup again.  Then copied the files from new one to old one and changed it back to pointing at the old appdata.  I now see STATS tab.  Running on demand report now.  Will take sometime since large server.

**Comment by rmilyard** [comment]
I ran on demand and seeing this in logs:

[cont-init.d] 10-set-uidgid: exited 0.
[cont-init.d] 20-setup: executing...
Advanced config file detected. Checking version ..

Latest 2.0.3 release found. Nothing to update.
Server ready
Please go to http://hostIP:hostPort/admin to configure settings
[cont-init.d] 20-setup: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2018-07-31 13:47:30: (log.c.217) server started
/usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): http://10.0.1.100:32400:32400/library/sections (URI::InvalidURIError)
from /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
from /usr/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
from /usr/lib/ruby/gems/2.3.0/gems/httparty-0.13.1/lib/httparty/request.rb:58:in `uri'
from /usr/lib/ruby/gems/2.3.0/gems/httparty-0.13.1/lib/httparty/request.rb:149:in `setup_raw_request'
from /usr/lib/ruby/gems/2.3.0/gems/httparty-0.13.1/lib/httparty/request.rb:90:in `perform'
from /usr/lib/ruby/gems/2.3.0/gems/httparty-0.13.1/lib/httparty.rb:521:in `perform_request'
from /usr/lib/ruby/gems/2.3.0/gems/httparty-0.13.1/lib/httparty.rb:457:in `get'
from /var/lib/nowshowing/plex.rb:35:in `get'
from /usr/local/sbin/combinedreport:110:in `getMovies'
from /usr/local/sbin/combinedreport:396:in `main'
from /usr/local/sbin/combinedreport:460:in `<main>'
/usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): http://10.0.1.100:32400:32400/library/sections (URI::InvalidURIError)
from /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
from /usr/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
from /usr/lib/ruby/gems/2.3.0/gems/httparty-0.13.1/lib/httparty/request.rb:58:in `uri'
from /usr/lib/ruby/gems/2.3.0/gems/httparty-0.13.1/lib/httparty/request.rb:149:in `setup_raw_request'
from /usr/lib/ruby/gems/2.3.0/gems/httparty-0.13.1/lib/httparty/request.rb:90:in `perform'
from /usr/lib/ruby/gems/2.3.0/gems/httparty-0.13.1/lib/httparty.rb:521:in `perform_request'
from /usr/lib/ruby/gems/2.3.0/gems/httparty-0.13.1/lib/httparty.rb:457:in `get'
from /var/lib/nowshowing/plex.rb:35:in `get'
from /usr/local/sbin/combinedreport:110:in `getMovies'
from /usr/local/sbin/combinedreport:396:in `main'
from /usr/local/sbin/combinedreport:460:in `<main>'

Is this normal?
http://10.0.1.100:32400:32400/library/sections (URI::InvalidURIError)

**Comment by rmilyard** [comment]
Found my issue. Working fine now.

**Comment by ninthwalker** [comment]
Good! yea, no port in the plex server field. =)
