### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by b55555** [ninthwalker/NowShowing#82]
I've had a couple of settings not save after configuring them. Cron schedule and announcement emails.

**Comment by ninthwalker** [comment]
What version are you on?
And how do you know they are not saving? Do they not show in the web interface fields anymore?
Also if you check the /cfg/advanced.yaml file in the dockers appdata dir, do you see the cron saved there?

Thanks.

**Comment by b55555** [comment]
I'm on version 2.0.3 and when I first brought it up I tried to set the cron schedule to Sunday evening emails however it kept doing the Friday schedule setup as default. When trying to do the announcement email whatever I would end up putting in the announcement never stuck and it kept reverting back to the test message that was in there by default. 

I ended up just leaving the cron schedule to Friday morning as it was in the default settings.

**Comment by ninthwalker** [comment]
Are you running this docker in unraid, windows or other OS?
I know i've had a cpl people with mount settings inside windows that have sort of had something like this happen, but it was fixed by setting the correct settings inside the docker for windows app.

**Comment by b55555** [comment]
I'm running docker on ubuntu server. V16 I think but not entirely sure. 

With the announcement emails I can change the title of the email, save it, and that will reflect in testing the announcement. Just the body of the email never changes from the default.

**Comment by ninthwalker** [comment]
Closing for now
