### ISSUE TITLE
Stats display order on web

### ISSUE THREAD

**Issue by weighsone** [ninthwalker/NowShowing#84]
Displaying the Tautulli stats at the top of the page when enabled for web seems counter intuitive. 
As an optional and "fun" feature I would expect this info to appear at the bottom of the page.

Could there be an option to choose this on the Stats page whether to generate it at the bottom (below new seasons) or the top (Above new movies, where it is now) of the main content?

**Comment by ninthwalker** [comment]
Hi, sorry for not responding sooner. Real life catches up sometimes.
I plan on doing some more development in the near future and can look into adding that option possibly.
Although I've always thought of the web page display and the email look as more of a default template. A lot of people like to change the look to customize for themselves, including me.

The webpage and the email files are both editable by you to do what you want and you could cut/paste the code for the webpage stats in the bottom if you would like instead.

files to change:
email_body.erb or web_body.erb

**Comment by ninthwalker** [comment]
I looked real quick, and the stats section in the web_body.erb is commented at where it starts.
If usuing the orginal unedited file, you would cut the lines from 115-340 and paste the at the bottom or some place you wanted.

Save a backup of the original in case you mess something up.
Let me know if that helps. Thanks.

**Comment by ninthwalker** [comment]
Closing this for now. Probably wont end up adding an option, and you can customize  the template as needed.
 Thanks.
