### ISSUE TITLE
TV Shows Fail to Update

### ISSUE THREAD

**Issue by discreet** [ninthwalker/NowShowing#85]
This error message started showing up in the logs and I noticed none of the newly added TV shows are showing in any of the reports.

`E, [2018-08-26T11:52:19.457840 #39444] ERROR -- : Something failed. Most likely metadata related. If you see this error all the time, turn on debugging and open an issue on github.`

There doesn't seem to be information on how to enable debug logging or view the logs directly inside the Docker container. All movies are reporting accurately.

**Comment by ninthwalker** [comment]
Hi, sorry for not responding earlier. real life catches up sometimes.
That error can be ignored unless you experience it a lot. Sometimes the matching against theTVDB is not the greatest on their end. 

Then again, sometimes it's the metadata on the plex side is off, and when it looks for that on tvdb it can't match either.

To enable verbose logging you need to run the report from the command line.
See The Wiki section on [command line options](https://github.com/ninthwalker/NowShowing/wiki/v2-Command-Line-Options)

**Comment by ninthwalker** [comment]
Closing for now, let me know if you still need help with your issue. Thanks
