### ISSUE TITLE
Email Fails to Send without From Field

### ISSUE THREAD

**Issue by discreet** [ninthwalker/NowShowing#86]
In the Email settings unless there is the actual email address in the `From` field the report fails to send. In the past you were able to have an alias be in the `From` field and still send the email.

eg. Instead of `From plexserver@gmail.com` you could do `Plex Updates` and it would send as `Plex Updates <plexserver@gmail.com>`.

**Comment by ninthwalker** [comment]
Sorry I didn't reply sooner. Not sure if you are still around or this is still an issue for you.
But I use a one name word in the 'From' field (ie: 'ninthwalker') on the email settings page and works fine for me. I use gmail as the provider, so not sure if every email provider supports that however.

Oh, I'm assuming you are on v2 as well.
Let me know, thanks.

**Comment by ninthwalker** [comment]
Closing for now, let me know if still an issue. Thanks.
