### ISSUE TITLE
Web page not updating

### ISSUE THREAD

**Issue by quite-shadow** [ninthwalker/NowShowing#87]
I am using v2 that came with Plexguide. The email is working, but the web page will not update at all. Stays on the default. Please point me in the right direction to try to fix this. Thanks.

**Comment by ninthwalker** [comment]
Not familiar with plexguide, but i think he just pulls the latest version from each apps docker hub.
So if it's just the basic NowShowing install, a couple things to check would be:

On the 'Report' tab. Is the Report Type set to Web only or web and email?

Maybe it did update but you are seeing a bad cache. Try clearing your browser cache, forcing a refresh, check with a different browser, etc.

Check logs for any errors?

Try that and let me know.
Thanks.

**Comment by quite-shadow** [comment]
Report type is web only.

Clearing cache and trying a different browser yielded no results

I'm not seeing any errors in the logs.

**Comment by quite-shadow** [comment]
This is what I got when trying to run report via command line:

docker exec nowshowing webreport --verbose
/usr/local/sbin/webreport:113:in `[]': no implicit conversion of String into Integer (TypeError)
        from /usr/local/sbin/webreport:113:in `block in getMovies'
        from /usr/local/sbin/webreport:112:in `each'
        from /usr/local/sbin/webreport:112:in `getMovies'
        from /usr/local/sbin/webreport:397:in `main'
        from /usr/local/sbin/webreport:454:in `<main>'

**Comment by ninthwalker** [comment]
Sorry it's been a while, was on vacation.
I can't replicate your error at all, and not quite sure what to check from here.
I don't know if the Plexguide thing is doing something different or not. IF you are able to do a standalone install of NowShowing and test that way, it might give us a better idea.

**Comment by quite-shadow** [comment]
Ok. I'll give it a try after the holidays. Thanks

**Comment by ninthwalker** [comment]
Closing this for now. Let me know if there is anything else i might be able to help with.
