### ISSUE TITLE
Settings to setup with Synology NAS?

### ISSUE THREAD

**Issue by asif5th** [ninthwalker/NowShowing#95]
Can anyone provide instructions in terms of how to set up with a Synology NAS? I'm using Docker. Not sure what the folder structure or environment settings are. Thanks

**Comment by ninthwalker** [comment]
Sorry, I don't have as much time to work on this Project these days and also don't have  Synology. I did see one post in the Unraid forums under this docker project support forums that said he got it working. Synology implements docker a bit diff so I'm not able to check into how to configure it there. Sorry.
