### ISSUE TITLE
Cover artwork

### ISSUE THREAD

**Issue by almulder** [ninthwalker/NowShowing#97]
Is there anyway to just pull the artwork from plex itself? This way the cover matches the same cover I selected (Or custom cover i made) in both screens. 

maybe same for info, just pull from plex as i also keep getting issues in my log for thetvdb.com not being able to connect. So right now it dose not pull any covers for tv shows, only movies (And the covers don't match whats in plex)

**Comment by ninthwalker** [comment]
Sorry i never responded. Real life caught up and i dont have much time to work on side projects anymore. To pull artwork from plex is not that feasible unfortunately. It's possible, but then to make the website work you would have to host the images from plex yourself, and not everyone has a setup to do that. The TVDB is kind of flaky, but not much else out there for the moment for tv api's.
