### ISSUE TITLE
Not reporting on certain shows.

### ISSUE THREAD

**Issue by Zeppyartaxes** [ninthwalker/NowShowing#98]
Doesn't show certain shows being added in the email report. so far I've noticed The Mandalorian and His Dark Materials. Both are getting added to my plex but the email doesn't contain them.

**Comment by Zeppyartaxes** [comment]
Episode one and two of The Mandalorian came through in last nights email when episode two was added.

**Comment by ninthwalker** [comment]
Sorry, I never responded. real life caught up and I don't have time to work on these side projects like I used to.

**Comment by ninthwalker** [comment]
Also, for your original comment, sometimes it fails with the TVDB has issues, which it seems to have a lot of these days. When their API comes back up, then episodes that were missed usually show up then.
